
name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: fazendo pull do repositório Git
        uses: actions/checkout@v2

      - name: diga oi para mazur
        run: echo "oii mazur"
